config/routes.rb
Rails.application.routes.draw do
  get 'doses/new'
  get 'doses/create'
  get 'doses/edit'
  get 'doses/update'
  get 'doses/destroy'
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @ingredients = Ingredient.where(cocktail_id: @cocktail.id)
    @all_ingredients = Ingredient.all
    # @doses = Dose.where(cocktail_id: @cocktail.id)
    # @doses = Ingredient.joins(:doses).where(doses: { cocktail_id: @cocktail.id })
    @doses = Ingredient.joins(:doses).select('ingredients.name,doses.description').where(doses: { cocktail_id: @cocktail.id })
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(set_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @cocktail.update(set_params)
      # redirect_to cocktail_path(@cocktail)
      redirect_to cocktails_path
    else
      render :new
    end
  end

  def destroy
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def set_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
  end

  def create
    @dose = Dose.new(set_params)
    @dose.cocktail_id = params[:cocktail_id]
    @dose.ingredient_id = params[:dose][:ingredient_id]

    @dose.save

    redirect_to cocktail_path(@dose.cocktail_id)
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def set_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show]

  def index
  end

  def show

  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/destroy.html.erb
<h1>Cocktails#destroy</h1>
<p>Find me in app/views/cocktails/destroy.html.erb</p>

app/views/cocktails/edit.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "Update", class: "btn btn-primary" %>
  <%= link_to "Cancel", cocktails_path, class: "btn btn-danger"%>
<% end %>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path('main_banner') %>);">
  <div class="container">
    <h1>Drank a glass of cocktail <strong>excellent</strong> for the head...</h1>
    <p>A cocktail can be made by the bartender. But the cocktail also can be made by the chef.</p>
    <%= link_to new_cocktail_path do %>
      <button class="btn btn-warning">Create Cocktail</button>
    <% end %>
  </div>
</div>

<div class="container-card">
  <div class="row">

    <% @cocktails.each do |cocktail| %>
      <div class="col-sm-4 col-sm-offset-3">
        <div class="card mb-3" style="max-width: 540px;">

          <div class="row no-gutters">
            <div class="col-md-4">
              <%= link_to cocktail_path(cocktail.id) do %>
                <%= cl_image_tag cocktail.photo, width: 200, height: 300, crop: :fill %>
              <% end %>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title"><%= cocktail.name %></h5>
                  <%= link_to edit_cocktail_path(cocktail.id) do %>
                    <i class="fa fa-edit"></i>
                  <% end %>
                  <%= link_to new_cocktail_path, method: :delete, data: { confirm: "Delete #{cocktail.name}?" } do %>
                    <i class="fa fa-trash-alt"></i>
                  <% end %>
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
              </div>
            </div>
          </div>

        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/cocktails/new.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "Save", class: "btn btn-primary" %>
  <%= link_to "Cancel", cocktails_path, class: "btn btn-danger"%>
<% end %>

app/views/cocktails/show.html.erb
<hr>
<h1><%= @cocktail.name %> </h1>
<hr>
<%= link_to cocktails_path do %>
  <i class="fa fa-history"></i> Back to list
<% end %>
<br>
<br>
<h3>Ingredients</h3>
<%= link_to new_cocktail_path do %>
  <i class="fa fa-plus"></i> Add ingredient
<% end %>

<hr>
<ul>
  <% @ingredients.each do |ingredient| %>
    <li>
      <%= ingredient.name %>
    </li>
  <% end %>
</ul>

<hr>
<ul>
  <% @doses.each do |dose| %>
    <li>
      <%= dose.name %>
      <%= dose.description %>
    </li>
  <% end %>
</ul>

<% if @dose.errors.any? %>
  <div class="errors-container">
    <ul>
      <% @dose.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :ingredient %>
  <%= f.input :description %>
  <%= f.submit "Add ingredient", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/update.html.erb
<h1>Cocktails#update</h1>
<p>Find me in app/views/cocktails/update.html.erb</p>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/edit.html.erb
<h1>Doses#edit</h1>
<p>Find me in app/views/doses/edit.html.erb</p>

app/views/doses/update.html.erb
<h1>Doses#update</h1>
<p>Find me in app/views/doses/update.html.erb</p>

app/views/ingredients/create.html.erb
<h1>Ingredients#create</h1>
<p>Find me in app/views/ingredients/create.html.erb</p>

app/views/ingredients/destroy.html.erb
<h1>Ingredients#destroy</h1>
<p>Find me in app/views/ingredients/destroy.html.erb</p>

app/views/ingredients/edit.html.erb
<h1>Ingredients#edit</h1>
<p>Find me in app/views/ingredients/edit.html.erb</p>

app/views/ingredients/index.html.erb
<h1>Ingredients#index</h1>
<p>Find me in app/views/ingredients/index.html.erb</p>

app/views/ingredients/new.html.erb
<h1>Ingredients#new</h1>
<p>Find me in app/views/ingredients/new.html.erb</p>

app/views/ingredients/show.html.erb
<h1>Ingredients#show</h1>
<p>Find me in app/views/ingredients/show.html.erb</p>

app/views/ingredients/update.html.erb
<h1>Ingredients#update</h1>
<p>Find me in app/views/ingredients/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- #F4F4F4 -->
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style = "background-color: #2B2B2B; color: white;" >
      <%= link_to cocktails_path, class: "navbar-brand" do %>
        <%= cl_image_tag("Final_cocktail_qoqt1q") %>ICocktail
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto" style = "color: white;">
          <li class="nav-item">
            <%= link_to "SignUp", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= cl_image_tag "user_avatar_byiami", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      </div>
    </div>

    <%= yield %>

  </body>


</html>